Add debug: true

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,3 +38,11 @@ jobs:
 
       - name: Run tests
         run: ./scripts/test
+  prevent-debug-release:
+    name: Prevent Debug SDK Release
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          echo "This SDK was built in debug mode, this job is a failsafe to prevent releasing debug SDKs"
+          echo "Remove 'debug: true' from your Stainless config."
+          exit 1
